import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { requireUser } from '@/lib/auth';

export async function GET() { try { await requireUser(); return NextResponse.json(await db.folder.findMany({ include: { _count: { select: { files: true, children: true } } }, orderBy: { name: 'asc' } })); } catch { return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); } }
export async function POST(req: Request) { try { const userId = await requireUser(); const { name, parentId } = await req.json(); if (!name || typeof name !== 'string' || name.length > 120) return NextResponse.json({ error: 'Invalid folder name' }, { status: 400 }); if (parentId && !(await db.folder.findUnique({ where: { id: parentId } }))) return NextResponse.json({ error: 'Invalid parent' }, { status: 400 }); const folder = await db.folder.create({ data: { name: name.trim(), parentId: parentId || null } }); await db.auditLog.create({ data: { action: 'folder_create', entityId: folder.id, userId } }); return NextResponse.json(folder, { status: 201 }); } catch { return NextResponse.json({ error: 'Folder already exists or could not be created' }, { status: 400 }); } }
export async function PATCH(req: Request) { try { const userId = await requireUser(); const { id, name, parentId } = await req.json(); if (id === parentId) return NextResponse.json({ error: 'A folder cannot contain itself' }, { status: 400 }); const descendants = await descendantsOf(id); if (parentId && descendants.has(parentId)) return NextResponse.json({ error: 'Circular folder relationship' }, { status: 400 }); const folder = await db.folder.update({ where: { id }, data: { ...(name ? { name: String(name).trim() } : {}), ...(parentId !== undefined ? { parentId: parentId || null } : {}) } }); await db.auditLog.create({ data: { action: 'folder_move', entityId: id, userId } }); return NextResponse.json(folder); } catch { return NextResponse.json({ error: 'Unable to update folder' }, { status: 400 }); } }
export async function DELETE(req: Request) { try { const userId = await requireUser(); const id = new URL(req.url).searchParams.get('id'); if (!id) return NextResponse.json({ error: 'Missing id' }, { status: 400 }); const folder = await db.folder.delete({ where: { id } }); await db.auditLog.create({ data: { action: 'folder_delete', entityId: id, userId } }); return NextResponse.json(folder); } catch { return NextResponse.json({ error: 'Unable to delete folder' }, { status: 400 }); } }
async function descendantsOf(id: string) { const seen = new Set<string>(); const queue = [id]; while (queue.length) { const current = queue.shift() as string; const children = await db.folder.findMany({ where: { parentId: current }, select: { id: true } }); for (const child of children) if (!seen.has(child.id)) { seen.add(child.id); queue.push(child.id); } } return seen; }
